#!/bin/bash
# Embed the client source in the Worker (Python Workers only bundle .py modules). Run by scripts/build.sh.
# Generates src/client_src.py; don't edit it by hand.
set -e
cd "$(dirname "$0")/.."
python3 - <<'PY'
import hashlib
src = open("client/channel.py", encoding="utf-8").read()
sha = hashlib.sha256(src.encode("utf-8")).hexdigest()
open("src/client_src.py", "w", encoding="utf-8").write(
    '"""Generated by client/gen.sh from client/channel.py. Do not edit."""\n'
    f'PATH = "/client/channel.py"\nSHA256 = "{sha}"\nSRC = {src!r}\n')
print(f"client_src.py  sha256={sha[:16]}…")
PY
