#!/bin/bash
# Embed assets/fonts/*.woff2 in the Worker (Python Workers only bundle .py modules). Generates src/fonts_src.py; don't edit it by hand.
# Why self-host instead of Google Fonts: external fonts send every visitor's IP to a third party,
# which contradicts "IPs are erased after 30 days" (D28). Font license: SIL OFL 1.1, see assets/fonts/LICENSE.txt
set -e
cd "$(dirname "$0")/.."
python3 - <<'PY'
import base64, glob, hashlib, os
fonts = {}
for p in sorted(glob.glob("assets/fonts/*.woff2")):
    b = open(p, "rb").read()
    fonts[os.path.basename(p)] = (base64.b64encode(b).decode(), hashlib.sha256(b).hexdigest()[:10])
with open("src/fonts_src.py", "w") as f:
    f.write('"""Generated by assets/gen_fonts.sh from assets/fonts/*.woff2. Do not edit."""\n')
    f.write("FONTS = {\n")
    for name, (b64, h) in fonts.items():
        f.write(f"    {name!r}: ({b64!r}, {h!r}),\n")
    f.write("}\n")
    # Social preview card and site icons (assets/img/*.png|ico, made by assets/gen_og.sh and gen_icons.sh)
    f.write("IMAGES = {\n")
    for p in sorted(glob.glob("assets/img/*.png") + glob.glob("assets/img/*.ico")):
        b = open(p, "rb").read()
        f.write(f"    {os.path.basename(p)!r}: {base64.b64encode(b).decode()!r},\n")
    f.write("}\n")
print("fonts_src.py:", ", ".join(f"{k} ({len(v[0])//1024} KB b64)" for k, v in fonts.items()))
PY
