#!/bin/bash
# Generate the modules the Worker needs (Python Workers only bundle .py files). scripts/dev.sh and
# scripts/deploy.sh run this first. The outputs are in .gitignore; never edit them.
#   src/client_src.py     client/channel.py, with its sha256
#   src/fonts_src.py      assets/fonts/*.woff2 and assets/img/*
#   src/changelog_src.py  CHANGELOG.md
set -e
cd "$(dirname "$0")/.."
client/gen.sh
assets/gen_fonts.sh
python3 - <<'PY'
src = open("CHANGELOG.md", encoding="utf-8").read()
open("src/changelog_src.py", "w", encoding="utf-8").write(
    '"""Generated by scripts/build.sh from CHANGELOG.md. Do not edit."""\n'
    f"SRC = {src!r}\n")
print(f"changelog_src.py  {src.count(chr(10) + '## ')} entries")
PY
